name 'my_cookbook'
maintainer 'Rongbing Miao'
maintainer_email 'rbmiao@gmail.com'
license 'all_rights'
description 'Installs/Configures my_cookbook'
long_description 'Installs/Configures my_cookbook'
version '0.1.0'
